DamSword.Web/Models/Shared/AjaxErrorModel.cs
namespace DamSword.Web.Models.Shared
{
    public class AjaxErrorModel
    {
        public string Message { get; set; }
    }
}

DamSword.Web/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DamSword.Web.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("~/Views/Shared/Components/Navigation/Navigation.cshtml");
        }
    }
}

DamSword.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <title>@ViewBag.Title | SoD</title>
    
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    
    <link rel="stylesheet" href="/lib/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/lib/bootstrap-3.3.7/css/bootstrap-theme.css">
    <script src="/lib/jquery-3.2.0/js/jquery-3.2.0.js"></script>
    <script src="/lib/bootstrap-3.3.7/js/bootstrap.js"></script>
    <script src="/lib/bootstrap-validator-0.11.9/js/validator.js"></script>
    <script src="/lib/bootstrap-notify-3.1.3/js/bootstrap-notify.js"></script>
    <script src="/lib/bootstrap-toolkit-2.6.3/js/bootstrap-toolkit.js"></script>
    <script src="/lib/underscore-1.8.3/js/underscore.js"></script>
    
    <link rel="stylesheet" href="/styles/theme.css">
    <script src="/lib/app/notify.js"></script>
    <script src="/lib/app/actions.js"></script>
</head>
<body>
    @if (!CurrentUser.IsAnonymous)
    {
        @await Component.InvokeAsync("Navigation")
    }

    <div class="container-fluid">
        @if (!CurrentUser.IsAnonymous && ViewBag.HideTitleHeader != true)
        {
            <h4 id="title-header" class="visible-xs">@ViewBag.Title</h4>
        }

        @RenderBody()
    </div>
</body>
</html>