DamSword.Web/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DamSword.Web.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("~/Views/Shared/Components/Navigation/Navigation.cshtml");
        }
    }
}

DamSword.Web/Controllers/DashboardController.cs
using System.Linq;
using DamSword.Common;
using DamSword.Data;
using DamSword.Data.Entities;
using DamSword.Data.Repositories;
using DamSword.Watch;
using DamSword.Web.Attributes;
using Microsoft.AspNetCore.Mvc;

namespace DamSword.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        [HttpGet]
        public IActionResult Details()
        {
            return View("~/Views/Dashboard/Details.cshtml");
        }

        [HttpPost]
        public IActionResult Details(string test)
        {
            Person person;
            if (ServiceLocator.Resolve<IPersonRepository>().Count() == 0)
            {
                person = new Person();
                
                var webResourceId = ServiceLocator.Resolve<IWebResourceRepository>()
                    .First(r => r.Name == "VKontakte", r => r.Id);

                ServiceLocator.Resolve<IPersonRepository>().Save(person);
                ServiceLocator.Resolve<IUnitOfWork>().Commit();

                ServiceLocator.Resolve<IMetaNameRepository>().Save(new MetaName
                {
                    PersonId = person.Id,
                    NameType = MetaNameType.Real,
                    NameKind = MetaNameKind.Alias,
                    Name = "TheQueen"
                });

                ServiceLocator.Resolve<IMetaAccountRepository>().Save(new MetaAccount
                {
                    PersonId = person.Id,
                    AccountId = "id158474048",
                    WebResourceId = webResourceId
                });

                ServiceLocator.Resolve<IUnitOfWork>().Commit();
            }
            else
            {
                person = ServiceLocator.Resolve<IPersonRepository>().Single(p => p.Names.Any(n => n.NameKind == MetaNameKind.Alias && n.Name == "TheQueen"));
            }

            ServiceLocator.Resolve<IWatch>().FetchOnline(new[] { person.Id });
            return View("~/Views/Dashboard/Details.cshtml");
        }
    }
}

DamSword.Web/Controllers/UserController.cs
using System.Linq;
using DamSword.Data.Entities;
using DamSword.Data.Repositories;
using DamSword.Web.Attributes;
using DamSword.Web.Models.User;
using Microsoft.AspNetCore.Mvc;

namespace DamSword.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;

        public UserController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        [HttpGet, Require(UserPermissions.ViewUsers)]
        public IActionResult List(string search)
        {
            var canManage = CurrentPermissions.Has(UserPermissions.ManageUsers);
            search = search?.ToLower() ?? string.Empty;

            var users = _userRepository.Select(u => u.Id == CurrentUser.Id || u.HierarchyLevel > CurrentUser.Hierarchy,
                u => new ListModel.User
                {
                    Id = u.Id,
                    Alias = u.Alias,
                    Login = canManage ? u.Login : null,
                    HierarchyLevel = canManage ? u.HierarchyLevel : int.MaxValue,
                    Permissions = canManage ? u.Permissions : UserPermissions.None
                })
                .Where(u => 
                    u.Id.ToString().ToLower().Contains(search) ||
                    u.Alias.ToLower().Contains(search) ||
                    canManage && (u.Login.ToLower().Contains(search) || u.HierarchyLevel.ToString().ToLower().Contains(search) || u.Permissions.ToString().ToLower().Contains(search)))
                .OrderBy(u => u.Alias)
                .ThenBy(u => u.HierarchyLevel)
                .ToArray();

            return View("~/Views/User/List.cshtml", new ListModel
            {
                Search = search,
                Users = users
            });
        }
    }
}

DamSword.Web/Views/Shared/Components/Navigation/Navigation.cshtml
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-controller="Dashboard" asp-action="Details" class="navbar-brand" id="brand-logo"><img id="brand-logo-image" src="/favicon-32x32.png" /> Sword of Damocles</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li bs-navigation="true"><a asp-controller="Dashboard" asp-action="Details" bs-navigation="true">Dashboard</a></li>
                <li bs-navigation="true"><a asp-controller="User" asp-action="List" bs-navigation="true">User List</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@CurrentUser.User.Alias <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Account" asp-action="">Settings</a></li>
                        <li><a asp-controller="Account" asp-action="Logout" >Exit</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>